### ISSUE TITLE
Adequação do plugin para compatibilidade com o BPC

### ISSUE THREAD

**Issue by thallesoliveira** [dsgoficial/pto_controle#2]
Foram observadas divergências entre a modelagem de dados que o BPC web espera para ser carregado os pontos de controle por gpkg e o gpkg oriundo deste plugin. 

Tendo em vista o os outros pontos ja carregados, solicito a adequação do plugin para que tenhamos compatibilidade.

Segue em anexo tanto o padrão  de nomes de arquivos esperada na importação de anexos como o gpkg para carga de pontos em lote. 

[estrutura_pasta_modelo_gpkg.zip](https://github.com/dsgoficial/pto_controle/files/9873078/estrutura_pasta_modelo_gpkg.zip)

**Comment by dinizime** [comment]
Verificando o anexo tem alguns pontos que nós consideramos incorretos:

- O nome do ponto está com zero a esquerda, o correto devendo ser PE-HV-21
- O zip do RINEX não deveria conter uma pasta dentro, e sim os arquivos .n, .o, e .g
- O arquivo PE-HV-021_CROQUI está incorreto, acredito que deveria ser o arquivo de processamento. Como existem os casos relativos estático e PPP acredito que podemos padronizar como _PROCESSAMENTO, nesta caso ficando PE-HV-21_PROCESSAMENTO.

Quanto ao gpkg vamos alterar para ficar igual a esse exemplo, tendo em vista que seria mais trabalhoso para você corrigir conforme nosso padrão.

**Comment by thallesoliveira** [comment]
Mandei o arquivo anexo errado, peço desculpas. 
Segue o arquivo correto que ja consegui importar no BPC. Os erros citados, além do CROQUI, já haviam sido tratados.



[PE-HV-21.zip](https://github.com/dsgoficial/pto_controle/files/9879411/PE-HV-21.zip)

**Comment by dinizime** [comment]
Não vai ter zip do RINEX então?

Porque baixando qualquer ponto do RS aqui (que teoricamente foram os primeiros pontos carregados no BPC) eles estão com RINEX zipado.

No caso dos pontos do RS nós utilizavamos o final _IMPLEMENTACAO_PPP para o arquivo de processamento. Como existem pontos processados por PPP e por RE, acredito que podemos utilizar o padrão _PROCESSAMENTO. No caso desse zip está _CROQUI (que não faz sentido, pois o conteúdo do arquivo é um arquivo de processamento).

**Comment by thallesoliveira** [comment]
Conversei com o Ten Marcel, é pra ter sim o PE-HV-21_RINEX.zip com os arquivos .0, .n e .g dentro.

**Comment by dinizime** [comment]
Esse .g é opcional no caso, depende do rastreador. Mas o .n e .o sempre tem

**Comment by MarcelFernandesCGEO** [comment]
Arquivos .zip gerados pelo passo _10 - Preparar insumos para carregamento no BPC_ agora seguem o modelo solicitado, gerando a seguinte sequência:

Arquivo .zip com o cod_ponto (cod_ponto.zip), contendo os seguintes arquivos:
  cod_ponto_RINEX.zip
  cod_ponto_PROCESSAMENTO.pdf
  cod_ponto_MONOGRAFIA.pdf
  cod_ponto_AEREA.jpg

Além disso, o .gpkg gerado se adequa as informações que são utilizadas pelo BPC.
