### ISSUE TITLE
Problemas de zip pelo macOS

### ISSUE THREAD

**Issue by thallesoliveira** [dsgoficial/pto_controle#3]
ao fazer a compressão em macOS, pela opção de comprimir da aba do botão direito do mouse, são gerados arquivos .DS_Stores e __MACOSX. Esses arquivos não são esperados no BPC, causando erros de importação. 

Workaround encontrado até o momento:

Usando um macOS é necessário comprimir os arquivos pelo terminal por meio da linha de comando rodada dentro da pasta onde estão os arquivos

zip -r dir.zip . -x ".*" -x "__MACOSX"

após isso é necessário ainda renomear o arquivo zipado para o codigo_do_ponto.zip (alterar o 'dir.zip')

o motivo é a presença de arquivos ocultos gerados pelo compressor do mac (.DS_Store and __MACOSX folders).

**Comment by dinizime** [comment]
Vamos resolver aqui porque é galho fraco. Mas em geral nós não garantimos o suporte para macOS nas ferramentas desenvolvidas pela DSG.

**Comment by MarcelFernandesCGEO** [comment]
Arquivos .DS_Store e pasta __MACOSX removidas na criação do .zip do BPC.

Solicito que sejam testadas as alterações.
